
@startuml
class ChecklistItem {
  - id: int
  --
  + visitId: int
  + exhibitId: int
  + name: String
  + startDate: Timestamp
  + done: boolean
}

class ChecklistService {
  + getChecklistItem (id: int): <ChecklistItem>
  + addChecklistItem (ticket: <Ticket>): void
  + updateChecklistItem (id: int, newChecklistItem: <ChecklistItem>): <ChecklistItem>
  + removeChecklistItem (id: int): void
  --
  + getChecklistItemList (visitId: int): List<ChecklistItem>
  + getChecklistItemList (exhibitId: int): List<ChecklistItem>
}
@enduml