
@startuml
class Route {
  - id: int
  --
  + visitId: int
  + graph: byte[]
}

class RouteService {
  + getRoute (id: int): <Route>
  + addRoute (route: <Route>): void
  + updateRoute (id: int, newRoute: <Route>): <Route>
  + removeRoute (id: int): void
}
@enduml
