include:
  project: ECPK-Public/PipelineLib
  ref: main
  file: common/.gitlab-ci.yml
#  file: java-base/.gitlab-ci.yml

variables:
  APP_ENV_HARBOR_PROJECT: proj-ebdz/docs
  APP_ENV_REPOSITORY_PATH: project/ebdz/ebdz-docs-env.git
  DOCKER_FILE: "docs/Dockerfile"
  APP_NAME: "ebdz-docs"
#  DEPLOY_APP: "false"
  SEC_IMAGE_SCAN_ENABLE: "false"
  ENV_BRANCH: main
  CHART_NAME: ebdz-docs
  CHART_PATH: charts/${CHART_NAME}

stages:
  - sast
  - sca
  - Test
  - Build
  - bca
  - dast
  - quality-gate
  - Release

build:
  extends: .base_build

test:
  extends: .base_test

release:
  extends: .base_release

deploy:
  extends: .base_deploy
  script:
    - tree ${APP_ENV_REPOSITORY_LOCAL_DIR}
    - cd ${APP_ENV_REPOSITORY_LOCAL_DIR}/${CHART_PATH}/${CI_ENVIRONMENT_SLUG}

    - echo "Updating image tag in values-${CI_ENVIRONMENT_NAME}.yaml"
    - yq eval ".image.tag = env(GitVersion_FullSemVer)" -i ${CHART_PATH}/values-${CI_ENVIRONMENT_NAME}.yaml

    # Commit and push changes
    - |
      if [ -z "$(git status --porcelain ${CHART_PATH}/values-${CI_ENVIRONMENT_NAME}.yaml)" ]; then
        echo "No changes to commit"
      else
        git add ${CHART_PATH}/values-${CI_ENVIRONMENT_NAME}.yaml
        git commit -m "[patch] update values for ${CI_ENVIRONMENT_NAME} environment" # [skip ci]
        echo "Updates from pipeline ${CI_PIPELINE_URL} in ${CI_PROJECT_PATH}"
        git push origin ${ENV_BRANCH}
      fi

  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        CI_ENVIRONMENT_NAME: dev
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        CI_ENVIRONMENT_NAME: prod
      when: manual

