@startwbs so_functional_model
!include ../../../static/theme/theme.puml
* Реестр СО
** Просмотр реестра
***_ Пагинация
***_ Просмотр количества записей
***_ Фильтрация
***_ Сортировка
***_ Настройка отображения колонок
*** Управляющие элементы записи реестра (Пиктограммы)
****_ Просмотр отчета
****_ Загрузка отчета
****_ Корректировка отчета
****_ Копирование отчета
****_ Удаление отчета
** Формирование отчета
***_ Просмотр и заполнение параметров отчета
***_ Заполнение наименования отчета
***_ Заполнение селекционного экрана
***_ Заполнение параметров формирования отчета
** Просмотр сформированного отчета
***_ Пагинация
***_ Просмотр количества записей
***_ Скачать
@endwbs
