@startmindmap
* Технологический радар
** Языки программирования
*** Используемое сейчас
**** Java
**** Python
**** Kotlin
*** Внедряется
**** Go
**** Rust
*** На исследовании
**** Scala
*** Устаревшее
**** PowerBuilder
** Инструменты
*** Используемое сейчас
**** Apache Airflow
**** Apache Kafka
**** PostgreSQL
*** Внедряется
**** ClickHouse
**** MinIO
*** На исследовании
**** dbt
**** Superset
*** Устаревшее
**** SQL Server
** Платформы
*** Используемое сейчас
**** Kubernetes
**** Docker
*** Внедряется
**** Yandex Cloud
*** На исследовании
**** OpenShift
*** Устаревшее
**** Bare-metal
** Методологии
*** Используемое сейчас
**** Agile
**** DevOps
*** Внедряется
**** Data Mesh
*** На исследовании
**** MLOps
@endmindmap
