@startgantt

'!theme superhero-outline
title Дорожная карта внедрения витрин данных и интеграции новых бизнесов

<style>
ganttDiagram {
  timeline {
    FontColor black
    FontStyle bold
    FontSize 16
 }
 task {
    RoundCorner 5
 }
 separator {
         BackgroundColor LightGray
         LineStyle 8.0;3.0
         LineColor Gray
         LineThickness 1.0
         FontSize 16
         FontStyle bold
         FontColor Black
         Margin 5
         Padding 6
     }
}
</style>

language ru
printscale quarterly zoom 15

Project starts the 1st of June 2025

--**Анализ и проектирование**--
[Начало проекта] happens at 1st of June 2025 and is 0% completed
[Анализ текущей инфраструктуры и проектирование витрины данных] starts at 1st June 2025 and requires 20 days and is 0% completed
[Сбор требований и разработка прототипа витрины данных для финансового домена] requires 15 days and is 0% completed

[Начало проекта] --> [Анализ текущей инфраструктуры и проектирование витрины данных]
[Анализ текущей инфраструктуры и проектирование витрины данных] --> [Сбор требований и разработка прототипа витрины данных для финансового домена]

--**Разработка витрин данных**--
[Разработка витрин данных по направлениям (финансы, BI, инвентаризация)] starts at 1st July 2025 and requires 30 days and is 0% completed
[Автоматизация ETL-процессов с использованием Apache Airflow] requires 20 days and is 0% completed

[Сбор требований и разработка прототипа витрины данных для финансового домена] --> [Разработка витрин данных по направлениям (финансы, BI, инвентаризация)]
[Разработка витрин данных по направлениям (финансы, BI, инвентаризация)] --> [Автоматизация ETL-процессов с использованием Apache Airflow]

--**Создание портала самообслуживания**--
[Создание портала самообслуживания для сотрудников] starts at 1st August 2025 and requires 25 days and is 0% completed
[Обеспечение доступа к отчетам по уровням доступа] requires 15 days and is 0% completed

[Автоматизация ETL-процессов с использованием Apache Airflow] --> [Создание портала самообслуживания для сотрудников]
[Создание портала самообслуживания для сотрудников] --> [Обеспечение доступа к отчетам по уровням доступа]

--**Интеграция новых бизнесов**--
[Интеграция новых бизнесов и их данных с минимальной доработкой ETL] starts at 1st September 2025 and requires 30 days and is 0% completed
[Обеспечение масштабирования витрин данных] requires 20 days and is 0% completed

[Обеспечение доступа к отчетам по уровням доступа] --> [Интеграция новых бизнесов и их данных с минимальной доработкой ETL]
[Интеграция новых бизнесов и их данных с минимальной доработкой ETL] --> [Обеспечение масштабирования витрин данных]

@endgantt

